@startuml

skin rose

title Join the server as duplicate name or color

...Only 2 player server...

== Join the server ==


Client1 -> Server: 3 JOIN Killian red
Server -> Client1: 1 OK

Client2 -> Server: 3 JOIN Guillaume red
Server -> Client2: 2 ERROR 2

Client2 -> Server: 3 JOIN Killian violet
Server -> Client2: 2 ERROR 1


Client2 -> Server: 3 JOIN Guillaume violet
Server -> Client2: 1 OK

Client3 -> Server: 3 JOIN Bob blue
Server -> Client3: 2 ERROR 3

@enduml